export const FETCH_PRODUCTS_SUCCESS = 'products/fetchSuccess'
export const REGISTER_USER_SUCCESS = 'users/registerSuccess'
export const LOGIN_USER_SUCCESS = 'users/loginSuccess'
export const GET_DETAIL_SUCCESS = 'products/getDetailSuccess'
export const GET_CATEGORIES_SUCCESS = 'categories/getSuccess'